name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 0 * * *" # once per day
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Health Endpoint
        run: |
          curl -L https://clubly-jet.vercel.app/api/health
